# -*- coding: utf-8 -*-
"""FashionMnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Gl0olnDRTiqc6JmiEJL_r9-yDIGd57t
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dropout,BatchNormalization,Conv2D,MaxPooling2D,Dense,Flatten

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()
print("x_train shape:", x_train.shape, "y_train shape:", y_train.shape)

Label	Description
0	T-shirt/top
1	Trouser
2	Pullover
3	Dress
4	Coat
5	Sandal
6	Shirt
7	Sneaker
8	Bag
9	Ankle boot

a=[25,39,8,67,90,5120,1000,234,1267,132]
plt.figure(figsize=(6,6))
for i in range(len(a)):
    plt.subplot(3,4,i+1)
    plt.imshow(x_train[a[i]])
    plt.title(y_train[a[i]])

x_train=x_train.reshape(-1,28,28,1)
x_test=x_test.reshape(-1,28,28,1)

x_train=x_train.astype('float32')
x_test=x_test.astype('float32')

x_train=x_train/255
x_test=x_test/255

y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

model=Sequential()
model.add(Conv2D(64,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(64, (3,3),activation='relu'))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy']) 

model.summary()

model.fit(x_train,y_train,batch_size=60,epochs=15,validation_split=0.2)

test_loss,test_acc=model.evaluate(x_test,y_test)
print('testloss',test_loss)
print('test accuracy',test_acc)

num=115
prediction=model.predict(x_test)
print(np.argmax(np.round(prediction[num])))

plt.imshow(x_test[num].reshape(28,28))
print("The Label is '{}'".format(y_test[num]))
plt.show()